[packages]
# Comprehensive list of required APT packages for Playwright/Chromium on Linux (Debian/Ubuntu-based images)
apt = [
  "fonts-liberation",
  "libasound2",           # libasound.so.2
  "libatspi2.0-0",        # libatspi.so.0
  "libatk-bridge2.0-0",   # libatk-bridge-2.0.so.0
  "libatk1.0-0",          # libatk-1.0.so.0
  "libcairo2",            # libcairo.so.2
  "libcups2",             # libcups.so.2
  "libdbus-1-3",          # libdbus-1.so.3
  "libexpat1",            # libexpat.so.1
  "libgbm1",              # libgbm.so.1
  "libglib2.0-0",         # libglib-2.0.so.0, libgio-2.0.so.0, libgobject-2.0.so.0
  "libgtk-3-0",
  "libnspr4",             # libnspr4.so
  "libnss3",              # libnss3.so, libnssutil3.so, libsmime3.so
  "libpango-1.0-0",       # libpango-1.0.so.0
  "libx11-6",             # libX11.so.6
  "libxcomposite1",       # libXcomposite.so.1
  "libxcb1",              # libxcb.so.1
  "libxdamage1",          # libXdamage.so.1
  "libxext6",             # libXext.so.6
  "libxfixes3",           # libXfixes.so.3
  "libxkbcommon0",        # libxkbcommon.so.0
  "libxrandr2",           # libXrandr.so.2
  "wget"
]
